{"uid":"40e12ab6cc4580ae","name":"Direct Access to Profile Page with Auth Cookie","fullName":"tests.web.admin.login_portal.test_session_persistence.TestSessionPersistence#test_direct_access_with_auth_cookie","historyId":"5117ddf8cf420496bc980e79bf5376de","time":{"start":1757078974620,"stop":1757078974620,"duration":0},"description":"Verify profile page can be accessed directly with authentication cookies","descriptionHtml":"<p>Verify profile page can be accessed directly with authentication cookies</p>\n","status":"broken","statusMessage":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","statusTrace":"request = <SubRequest 'user_auth' for <Coroutine test_direct_access_with_auth_cookie>>\nkwargs = {'runner': <utils.browser_config.Config object at 0x7fc022802e10>}\nunittest = False, func = <function user_auth at 0x7fc0280f42c0>\nsetup = <function _wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.setup at 0x7fc022a46660>\nfinalizer = <function _wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer at 0x7fc022ab4680>\n\n    @functools.wraps(fixture)\n    def _asyncgen_fixture_wrapper(request: FixtureRequest, **kwargs: Any):\n        unittest = fixturedef.unittest if hasattr(fixturedef, \"unittest\") else False\n        func = _perhaps_rebind_fixture_func(fixture, request.instance, unittest)\n        event_loop = kwargs.pop(event_loop_fixture_id)\n        gen_obj = func(\n            **_add_kwargs(func, kwargs, event_loop_fixture_id, event_loop, request)\n        )\n    \n        async def setup():\n            res = await gen_obj.__anext__()\n            return res\n    \n        def finalizer() -> None:\n            \"\"\"Yield again, to finalize.\"\"\"\n    \n            async def async_finalizer() -> None:\n                try:\n                    await gen_obj.__anext__()\n                except StopAsyncIteration:\n                    pass\n                else:\n                    msg = \"Async generator fixture didn't stop.\"\n                    msg += \"Yield only once.\"\n                    raise ValueError(msg)\n    \n            event_loop.run_until_complete(async_finalizer())\n    \n>       result = event_loop.run_until_complete(setup())\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py:347: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py:654: in run_until_complete\n    return future.result()\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py:329: in setup\n    res = await gen_obj.__anext__()\nconftest.py:73: in user_auth\n    page_instance = await runner.setup_auth_page(\"user\")\nutils/browser_config.py:130: in setup_auth_page\n    context = await self.context_init(storage_state=True, user_type=auth_mode, device_name=device_name)\nutils/browser_config.py:107: in context_init\n    session_file = await self.session_handler.create_session(user_type)\nutils/sess_handler.py:82: in create_session\n    email, password = self.load_credentials(user_type)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.sess_handler.SessionHandler object at 0x7fc022802fd0>\nuser_type = 'user'\n\n    def load_credentials(self, user_type):\n        mapping = {\n            \"user\": [\"USER_EMAIL\", \"USER_PASSWORD\"],\n            \"admin\": [\"ADMIN_EMAIL\", \"ADMIN_PASSWORD\"],\n            \"super_admin\": [\"SUPER_ADMIN_EMAIL\", \"SUPER_ADMIN_PASSWORD\"]\n        }\n    \n        # Default to user type if not in mapping\n        env_vars = mapping.get(user_type.lower(), [\"USER_EMAIL\", \"USER_PASSWORD\"])\n    \n        # Get credentials from environment variables\n        email = os.getenv(env_vars[0])\n        password = os.getenv(env_vars[1])\n    \n        if email and password:\n            return email, password\n        else:\n>           raise ValueError(f\"Credentials for {user_type} not found. Set {env_vars[0]} and {env_vars[1]} in your .env file.\")\nE           ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.\n\nutils/sess_handler.py:66: ValueError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop","time":{"start":1757078974620,"stop":1757078974620,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"playwright","time":{"start":1757078974620,"stop":1757078974836,"duration":216},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"runner","time":{"start":1757078974836,"stop":1757078974921,"duration":85},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"user_auth","time":{"start":1757078974921,"stop":1757078974974,"duration":53},"status":"broken","statusMessage":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py\", line 347, in _asyncgen_fixture_wrapper\n    result = event_loop.run_until_complete(setup())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py\", line 654, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py\", line 329, in setup\n    res = await gen_obj.__anext__()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/conftest.py\", line 73, in user_auth\n    page_instance = await runner.setup_auth_page(\"user\")\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/browser_config.py\", line 130, in setup_auth_page\n    context = await self.context_init(storage_state=True, user_type=auth_mode, device_name=device_name)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/browser_config.py\", line 107, in context_init\n    session_file = await self.session_handler.create_session(user_type)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/sess_handler.py\", line 82, in create_session\n    email, password = self.load_credentials(user_type)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/sess_handler.py\", line 66, in load_credentials\n    raise ValueError(f\"Credentials for {user_type} not found. Set {env_vars[0]} and {env_vars[1]} in your .env file.\")\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[{"name":"runner::finalizer","time":{"start":1757078975020,"stop":1757078975047,"duration":27},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"playwright::finalizer","time":{"start":1757078975048,"stop":1757078975054,"duration":6},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::3","time":{"start":1757078975054,"stop":1757078975054,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_close_event_loop","time":{"start":1757078975054,"stop":1757078975054,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_restore_policy","time":{"start":1757078975054,"stop":1757078975054,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1757078975054,"stop":1757078975054,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Authentication"},{"name":"severity","value":"critical"},{"name":"epic","value":"Admin Portal"},{"name":"tag","value":"asyncio"},{"name":"tag","value":"ui"},{"name":"parentSuite","value":"tests.web.admin.login_portal"},{"name":"suite","value":"test_session_persistence"},{"name":"subSuite","value":"TestSessionPersistence"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"3651-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.web.admin.login_portal.test_session_persistence"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"47cb460741456a40","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757078972116,"stop":1757078972116,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":9,"skipped":0,"passed":1,"unknown":0,"total":10},"items":[{"uid":"ba21794310ecc072","reportUrl":"https://009MHz.github.io/noov/39//#testresult/ba21794310ecc072","status":"passed","time":{"start":1757078372265,"stop":1757078372967,"duration":702}},{"uid":"1862827e7956452d","reportUrl":"https://009MHz.github.io/noov/38//#testresult/1862827e7956452d","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757077551583,"stop":1757077551583,"duration":0}},{"uid":"ee6e5ff910aad530","reportUrl":"https://009MHz.github.io/noov/37//#testresult/ee6e5ff910aad530","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757077270190,"stop":1757077270190,"duration":0}},{"uid":"5c979b4c535787d4","reportUrl":"https://009MHz.github.io/noov/37//#testresult/5c979b4c535787d4","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757076793345,"stop":1757076793345,"duration":0}},{"uid":"e27b8eca85aa6774","reportUrl":"https://009MHz.github.io/noov/36//#testresult/e27b8eca85aa6774","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757074479143,"stop":1757074479143,"duration":0}},{"uid":"dd0836ec306bb359","reportUrl":"https://009MHz.github.io/noov/34//#testresult/dd0836ec306bb359","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757073470088,"stop":1757073470088,"duration":0}},{"uid":"68c7259d7e221d75","reportUrl":"https://009MHz.github.io/noov/33//#testresult/68c7259d7e221d75","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757073029822,"stop":1757073029822,"duration":0}},{"uid":"9134a39eefb8eba3","reportUrl":"https://009MHz.github.io/noov/32//#testresult/9134a39eefb8eba3","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757072442186,"stop":1757072442186,"duration":0}},{"uid":"76cee683c2d8202","reportUrl":"https://009MHz.github.io/noov/31//#testresult/76cee683c2d8202","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757071998651,"stop":1757071998651,"duration":0}}]},"tags":["asyncio","ui"]},"source":"40e12ab6cc4580ae.json","parameterValues":[]}